apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "{{installName}}"
  namespace: installs
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "{{appId}}"
        install: "{{installId}}"
        org: "{{orgId}}"
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
      - name: shared-data
        mountPath: /usr/share/nginx/html
  volumes:
  - name: shared-data
    emptyDir: {}